export const wheelConfig = {
  slots: 20,
  centerX: 400,
  spinDuration: 5000,
  spinDeceleration: 0.95,
  centerY: 400,
  outerRadius: 560,
  innerRadius: 375,
  gapWidth: 10,
  cornerRadius: 15,
  prizes: [
    { image: 'gift.svg', value: '25' },
    { image: 'rose.svg', value: '25' },
    { image: 'bust.svg', value: 'Буст' },
    { image: 'heart.svg', value: '15' },
    { image: 'flowers.svg', value: '50' },
    { image: 'diamond.svg', value: '100' },
    { image: 'gift.svg', value: '25' },
    { image: 'rocket.svg', value: '50' },
    { image: 'bear.svg', value: '15' },
    { image: 'heart.svg', value: '15' },
    { image: 'ring.svg', value: '100' },
    { image: 'rose.svg', value: '25' },
    { image: 'bust.svg', value: 'Буст' },
    { image: 'trophy.svg', value: '100' },
    { image: 'bear.svg', value: '15' },
    { image: 'rose.svg', value: '25' },
    { image: 'flowers.svg', value: '50' },
    { image: 'gift.svg', value: '25' },
    { image: 'snake.svg', value: '400' },
    { image: 'rose.svg', value: '25' },
    { image: 'rocket.svg', value: '50' }
  ]
};